# Generated by Django 4.2.4 on 2023-08-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit',
        ),
    ]
